
SELECT * FROM room;

SELECT * FROM date;

SELECT * FROM hotel;

SELECT * FROM aggbookings;

SELECT * FROM bookings;
----------------------------------------------------------------------------
-- Revenue generated by different Booking Platform
SELECT booking_platform,
      SUM(revenue_realized)AS Revenue 
FROM bookings
GROUP BY booking_platform
ORDER BY Revenue DESC;
----------------------------------------------------------------------------
-- Revenue generated by different  City
SELECT  H.city, 
        SUM(revenue_realized)AS Revenue 
FROM bookings AS B 
JOIN hotel AS H
ON  B.property_id = H.property_id
GROUP BY  H.city
ORDER BY Revenue DESC;
----------------------------------------------------------------------------
-- Total Customer and  Revenue generated by different Property name and Property category
SELECT  H.property_name,
        H.category,
	SUM(revenue_realized)AS Revenue,
	COUNT(B.booking_id) AS Customer
FROM bookings AS B 
JOIN hotel AS H
ON  B.property_id = H.property_id
GROUP BY  H.property_name, H.category
ORDER BY H.category;
----------------------------------------------------------------------------
--Revenue by Room class
SELECT  R.room_class, 
        SUM(revenue_realized)AS Revenue
FROM bookings AS B 
JOIN room AS R
ON  B.room_category  = R.room_id
GROUP BY   R.room_class
ORDER BY Revenue DESC;
----------------------------------------------------------------------------
--Rating By Property Name 
SELECT  H.property_name,
        ROUND(AVG(B.ratings)) AS Rating
FROM bookings AS B 
JOIN hotel AS H
ON  B.property_id = H.property_id
GROUP BY  H.property_name;







